
services:
  backend:
    image: modestat/webproject25:latest
    ports:
      - "8284:8000"
    restart: always
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  frontend:
    image: modestat/webproject25-frontend:latest
    ports:
      - "8184:3030"
    restart: always
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge