#----------------------POST(CREATE)-------------------------
### Create new study
POST http://localhost:8000/api/studies
Content-Type: application/json

### Create a question
POST http://localhost:8000/api/studies/:studyId/questions
Content-Type: application/json


#---------------------GET-----------------------------------
### Get study by id
GET http://localhost:8000/api/studies/:studyId

### Get artifacts for sorting
GET http://localhost:8000/api/studies/artifacts

#---------------------PATCH(UPDATE)-------------------------
### Update study by id
PATCH http://localhost:8000/api/studies/:stuyId
Content-Type: application/json

### Update question in study
PATCH http://localhost:8000/api/studies/:studyId/questions/:questionId
Content-Type: application/json

#---------------------DELETE--------------------------------
### Delete/remove artifact from question
DELETE http://localhost:8000/api/studies/:studyId/questions/:questionId/artifacts/:artifactId

### Delete a artifact from the collection
DELETE http://localhost:8000/api/studies/artifacts/:artifactId

### Delete a question from study
DELETE http://localhost:8000/api/studies/:studyId/questions/:questionId
