@baseUrl = http://localhost:8000/api/survey
@studyId = 67fe5a81cdfd8b383b497476
@sessionId = 67fe5b6dcdfd8b383b497484
@questionId = 67fe5ae8cdfd8b383b49747a



POST {{baseUrl}}/{{studyId}}/sessions
Content-Type: application/json

{
  "deviceInfo": "Phone",
  "demographics": {
    "age": "25-35",
    "gender": "female"
  }
}
###

GET {{baseUrl}}/{{studyId}}/survey?page=0&sessionId={{sessionId}}

###
POST {{baseUrl}}/{{studyId}}/sessions/{{sessionId}}/{{questionId}}
Content-Type: application/json

{
  "answer": "positive",
  "answerType": "text",
  "skipped": false
}
###

POST {{baseUrl}}/{{studyId}}/sessions/{{sessionId}}/{{questionId}}
Content-Type: application/json

{
  "answer": "Yes, again",
  "answerType": "text",
  "skipped": false
}

###

PATCH {{baseUrl}}/{{studyId}}/sessions/{{sessionId}}/{{questionId}}
Content-Type: application/json

{
  "answer": "Actually, no.",
  "answerType": "text",
  "skipped": false
}

###

POST {{baseUrl}}/{{studyId}}/sessions/{{sessionId}}/{{questionId}}
Content-Type: application/json

{
  "skipped": true,
  "answerType": "text"
}
###

GET {{baseUrl}}/{{studyId}}/survey?page=999

###

POST {{baseUrl}}/{{studyId}}/sessions/{{sessionId}}/invalidquestionid123
Content-Type: application/json

{
  "answer": "Doesn't matter",
  "answerType": "text",
  "skipped": false
}
###

GET {{baseUrl}}/{{studyId}}/survey?page=0&sessionId={{sessionId}}
