# Register a new username

POST http://localhost:8000/api/auth/register


{
    "username": "John",
    "email": "john@gmail.com",
    "password": "johnk123"
}

# Login user
POST http://localhost:8000/api/auth/login

{
    "username": "bella",
    "password": "bella123"
}


{
    "_id": "681e06394c45b4da5f660109",
    "username": "bella",
    "email": "bella@gmail.com",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWUwNjM5NGM0NWI0ZGE1ZjY2MDEwOSIsImlhdCI6MTc0Njk4NDI1MywiZXhwIjoxNzQ5NTc2MjUzfQ.cc1DLNza-18xnbzwBL5rwvDFd72N_R-MDqYgmib6GGo"
}

# Logout user
http://localhost:8000/api/auth/logout

# getuser

{
    "data": {
        "id": "67e53e881733edaf16e75fd8",
        "username": "fredrik"
    }
}

