name: Dcoker Image CI/CD for webproject

#port on where it iwll run
on:
  push:
    branches: ["main"]
  pull:request:
    branches: ["main"]

jobs:
  test: 
    runs-on: ubuntu-latest #what system it runs on and their stesps
    steps:
      - uses: actions/checkout@v3 # it takes ocntent of our repository and deploys them inside this ubuntu server provided by github
      - uses: actions/setup-node@v3
        with: #specify with what param that node is
          node-version: 23.x
          cache: npm #if we want to have npm there
      - run: npm ci #intsalla exaclty the packages
      - name: some type of tetsing that we are doing
        run: npm run test #the same that we do in packge.json in scirpt exept it will do not local but on the github or somehting



 
build:
  runs-on: ubuntu-latest
  needs: test # it will not run unless test suceesd
  steps: 
    - uses: actions/checkout@v3 #checkout repo
    - uses: docker/login-action@v3 # u need to login before moving on
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: build and push our image to dockerhub
      uses: docker/buil-push-action@v5
      with:
        context: .
        file: Dockerfile    #file for docker
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME}}/idg2671_25:latest #deal with isseu of secret # u need yo go in github and then setyting and then actions -> secrets and paste in name field the DOCKERHUB or whatever other name in the github and your name docker name in secrets, we will also need to genereate access token from docker account center


# you also need a repo on docker account or soemhting


# for dpeloying go to temrinal
- password studyplatform
- the last hting i did was mkdir project-main, but we dont have docker compose.yaml

then write this: 
- mkdir scripts -> cd scirpts
-> nano copy.compose.yaml.sh
-> inside nano 6.2
#!/bin/bash 
#this is a bash scriptnto copy compose.yaml from github servers to our production server and to modify it a bit (as necessaru)
 set -e #if there is an error during execution, it will stop the rests cript if not it will consituye and we disable it at the end

#constants
REPO_URL="https://raw.githubusercotnetn.csom...sabrina"
COMPOSE_FILE="compose.yaml"
WD="/home/group4/project-main" #our working direcotry

#copying comspose yaml
curl -sS "${REPO_URL}/${COMPOSE_FILE}" |
       sed 's|build: .|image: sabrina23/reponame:latest|' > "${WD}/${COMPOSE_FILE}" | #which mean that lines that contians build caracters will be simple deleted, cause if not it will try to build form local file, and we wan tot download from ...,  > mean redirect to another file
       # sed 's|image:'   #s means substitute, and then u privde name of the image

 set +e


 then u save
 and then u make it accesutbale in terminal
 -> project.main/scripts$ chmod u+x copy.coompose.yaml.sh
 -rwxr--r--1 it mean it is executble
 bash copy.compose.yamk.sh
 then go cd .. and then ls
 then u shoudl see compose.yaml file
 and then somehting in the temrinal 

 then u need naother file to deploy, nano deploy.sh cretae a new file
 #/bin/bash

 #this script deploys a decoker compose project
 set -e

COMPOSE_FILE="compose.yaml"
WD="/home/group4/project-main"

docker compose -f "${WD}/${CONPOSE_FILE}" down
docker compose -f ${WD}/${COMPOISE_FILE} up -d


 set +e #for intereapting the execution 

 then go to temrinal nano runall.sh
 and write new nano scirpt

 set -e

SCRIPT_DIR="/home/group4/prject-main/scripts"

bash "${SCRIPT_DIR}/compy.compose.yaml.sh"
bash "${SCRIPT_DIR}/deploy.sh"
 set +e

 then move the deploy.sh ./scripts/deploy.sh
 and mv runall.sh ./scirpts/runall.sh

 an din project-mai nshoudl be compsoee.yaml and scirpts

 chmod u+x for deploy.sh and runall.sh 

 then u can run the files from folder scripts$ 

dockerize app and cretae github workflow to build and psuh a docker image to dockerhub

use this: https://group1.sustainability.it.ntnu.no for finding if it exists