name: Docker Images CI/CD for webproject

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-backend: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: Backend/package-lock.json
      - name: Install dependencies and run tests
        working-directory: ./Backend
        run: |
          npm ci
          npm run test
          
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: Frontend/package-lock.json
      - name: Install dependencies and run tests
        working-directory: ./Frontend
        run: |
          npm ci
          npm run test
          
  build-backend:
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]
    steps: 
      - uses: actions/checkout@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./Backend
          file: ./Backend/Dockerfile
          push: true
          tags: modestat/webproject25:latest
          
  build-frontend:
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]
    steps: 
      - uses: actions/checkout@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./Frontend
          file: ./Frontend/Dockerfile
          push: true
          tags: modestat/webproject25-frontend:latest
