name: Docker Image CI/CD for webproject

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 23.x
          cache: npm
      - run: npm ci
      - name: Run tests
        run: npm run test
        
  build:
    runs-on: ubuntu-latest
    needs: test
    steps: 
      - uses: actions/checkout@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./Backend
          file: ./Backend/Dockerfile
          push: true
          tags: modestat/project-backend:latest
      
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./Frontend
          file: ./Frontend/Dockerfile
          push: true
          tags: modestat/project-frontend:latest
